In [9]:
# home llms, office olm2
import warnings
warnings.filterwarnings("ignore", category=SyntaxWarning, message=".*escape sequence.*")

import httpx
from openai import OpenAI
import time
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv, find_dotenv
from statistics import mode
import ast
import re

#from aux_prompts import *
#from queries import criteria_text3
os.environ["OPENAI_API_KEY"] = 'hey' # for importing trialmind, api_key should be set beforehand
os.environ['TEMPERATURE'] = '0'

use = 'rogozin'
#use = 'cpp'

if use == 'hf':
    os.environ["BASE_URL"] = "https://router.huggingface.co/v1"
    os.environ["MODEL_NAME"] ='Qwen/Qwen3-14B'
    os.environ["OPENAI_API_KEY"] = os.getenv("HUGGINGFACE_HUB_TOKEN")
elif use == 'olm':
    os.environ["BASE_URL"] = "http://localhost:11434/v1"
    os.environ["MODEL_NAME"] ='qwen3:14b'
    os.environ["OPENAI_API_KEY"] = 'hey'
elif use == 'rogozin':
    os.environ["BASE_URL"] = "http://localhost:8501/v1"
    os.environ["MODEL_NAME"] ='/models/Qwen3.6-27B-UD-Q4_K_XL.gguf'#'ggml-org/gemma-3-1b-it-GGUF'
    os.environ["TRANSL_MODEL_NAME"] = '/models/Qwen3.6-27B-UD-Q4_K_XL.gguf'
    os.environ["OPENAI_API_KEY"] = 'hello'
elif use == 'sirius':
    os.environ["BASE_URL"] = "http://127.0.0.1:8082/v1"
    os.environ["MODEL_NAME"] ='Qwen3.6-27B'#'ggml-org/gemma-3-1b-it-GGUF'
    os.environ["OPENAI_API_KEY"] = 'hello'
    os.environ["TRANSL_MODEL_NAME"] = 'Qwen3.6-27B'
elif use == 'cloud':
    os.environ["BASE_URL"] = "http://51.250.66.187:8080/v1"
    os.environ["MODEL_NAME"] ='Qwen3.6-27B'
    #os.environ["TRANSL_MODEL_NAME"] = 'gemma-4-12B'
    os.environ["OPENAI_API_KEY"] = 'hey'
load_dotenv(find_dotenv(usecwd=True), override=True)
import glob


%load_ext autoreload
%autoreload 2

In [10]:
df1 = pd.read_csv('new_criteria_qwen36_27b.csv')

### small fixes

In [22]:
dfo = pd.read_csv('new_criteria_ana_en.csv')
dfo.PMID = dfo.PMID.apply(lambda x: str(x.split('/')[-1]))
print(dfo.shape)

dfe = pd.read_csv('common_errors_fixed.csv')
dfe['PMID_статьи'] = dfe['PMID_статьи'].apply(lambda x: str(x).split('.')[0])

def fix(x):
    if x['PMID'] in dfe['PMID_статьи'].values:
        row = dfe[dfe['PMID_статьи'] == x['PMID']]
        row_1 =  row[row['Номер_критерия']==1]
        row_2 =  row[row['Номер_критерия']==2]
        row_3 =  row[row['Номер_критерия']==3]
        for row_i in [row_1,row_2,row_3]:
            if row_i.shape[0]:
                i = str(row_i['Номер_критерия'].values[0]).split('.')[0]
                x[f's{i}'] = row_i['Оценка_Эксперт'].values[0]
                x[f'r{i}'] = row_i['Обоснование_Эксперт'].values[0]
                print('change', x['PMID'])
        return x
    else:
        return x

dfo = dfo.apply(lambda x: fix(x), axis=1)
ps_thresh = [1,1,0]
chosen_df = dfo[(dfo['s1']>=ps_thresh[0]
                    )&(dfo['s2']>=ps_thresh[1]
                        )&(dfo['s3']>=ps_thresh[2])]
dfo['accept'] = dfo[['s1','s2','s3']].apply(lambda x: True if (x['s1']>=ps_thresh[0]
                    )&(x['s2']>=ps_thresh[1]
                        )&(x['s3']>=ps_thresh[2]) else False, axis=1)

dfo.accept.value_counts()

(67, 7)
change 25139705
change 31399568
change 26995877
change 35343863
change 35343863
change 26438251
change 26438251
change 37773318
change 37773318
change 37773318
change 33676682
change 23719267
change 23719267
change 22845480
change 24789362
change 37686423
change 41213063
change 41213063
change 36801912
change 28465216
change 28465216
change 36129915
change 36627781
change 36627781
change 34898475
change 34898475
change 28903995
change 28903995
change 23585220
change 26468446
change 23656699
change 29466887
change 40526090
change 40526090
change 38378070

accept
False    40
True     27
Name: count, dtype: int64

In [24]:
from googletrans import SyncTranslator
import re
translator = SyncTranslator()
text = (dfo.iloc[:,4:-1].values).reshape(-1)
text = [re.sub(r'\b[нН][мМ][Рр][лЛ]\b','NSCLC', re.sub(r'\b[Кк][Рр][Рр]\b','CRC',i)) for i in text]
r = translator.translate([i for i in text], dest="en")
[i.text for i in r]#.text

['The article describes the clinical case of a 19-year-old patient with malignant peritoneal mesothelioma',
 'Crizotinib has been used to treat mesothelioma',
 'The effectiveness of crizotinib for CRC has not been assessed.',
 '"16 colorectal cancer cases"',
 'The abstract states that patients received inhibitors of various signaling pathways, including ALK/ROS1. Although crizotinib is an ALK/ROS1 inhibitor, it is not explicitly named in the abstract. We cannot confirm that it was the specific drug used in patients (it could be ceritinib, alectinib, lorlatinib, etc.)',
 'The abstract provides general data for the cohort (4 patients with CRC had a response), but is not linked to a specific drug.',
 'This is a review article summarizing current advances in targeted therapy for solid tumors. It does not include original patients, models or samples',
 'Crizotinib is mentioned in the abstract, but in association with NSCLC',
 'Therapeutic efficacy for CRC has not been assessed',
 'The study uses the CRC cell line Colo205 and related animal tumor models',
 'It is stated that crizotinib (both monotherapy and combination) was used to evaluate the effect on metastasis, and this effect was observed in all models tested, including Colo205',
 'The study evaluates the biologically and clinically relevant preclinical outcome of reduced metastasis',
 'The abstract mentions CRC as one example of tumors where ROS1 rearrangements may be observed',
 'Crizotinib is mentioned as a drug to which patients have developed resistance',
 'The study evaluates the effectiveness of the new drug DS-6051b, not crizotinib',
 'CRC is mentioned as an example ("KRAS against the use of cetuximab and panitumumab in colorectal cancer")',
 'Crizotinib mentioned in the context of NSCLC and ALK fusions',
 'The article does not evaluate the effectiveness of crizotinib in CRC',
 'A cohort of 1889 CRC samples is analyzed',
 'Crizotinib is mentioned in the introduction as a drug that has shown good results in the treatment of lung cancer with ALK/ROS1 rearrangements',
 'Therapeutic efficacy assessment for CRC is not available',
 'CRC cell line - KM12SM ("the KM12SM colorectal cancer cells containing the TPM3-NTRK1 gene fusion"). Corresponding animal models are also used (“in in vivo KM12SM cell models”)',
 'In vitro: "KM12SM cells were sensitive to the tropomyosin-related kinase-A inhibitors crizotinib and entrectinib". In vivo: "in in vivo KM12SM cell models, treatment with crizotinib delayed the progression of liver metastases..."',
 'The antitumor activity of crizotinib in the CRC model (KM12SM) is assessed by delaying the progression of metastases: “treatment with crizotinib delayed the progression of liver metastases, but not that of brain tumors”',
 '"human colorectal cancer (CRC) cell line (HCA-7)"; "CRC tissue microarray"',
 '"Addition of the dual MET/RON tyrosine kinase inhibitor, crizotinib, restored cetuximab sensitivity in SC." Crizotinib is used to overcome cetuximab resistance in a CRC model',
 'Evaluates the therapeutic efficacy of crizotinib based on the biologically significant outcome of “restored cetuximab sensitivity in SC.”',
 'CRC is mentioned only once in the introduction as an example of a disease associated with ROS1 ("which is involved in the formation of non-small cell lung cancer (NSCLC), gastric adenocarcinoma, colorectal cancer, and other malignant tumors")',
 'Crizotinib is mentioned in the context of treatment of NSCLC: 1. "only crizotinib was approved for the treatment of advanced ROS1-positive NSCLC" 2. "Since the approval of crizotinib as multi-targeted ALK/MET/ROS1 kinase inhibitor for ALK-mutated NSCLC therapy"',
 'All discussion of the effectiveness of crizotinib applies to NSCLC',
 'The title refers to a patient with metastatic colorectal cancer: "Metastatic Colorectal Carcinoma Patient". There is a description of a patient with CRC',
 'Crizotinib (along with Alectinib and Lorlatinib) was used as a treatment for the patient: "Clinical Responses to Crizotinib, Alectinib, and Lorlatinib..."',
 'The name indicates "Clinical Responses", which involves assessing clinical response. However, without an abstract it is impossible to confirm: Which outcomes were assessed (ORR, PFS, OS, etc.); Was quantitative data provided; What was the specific response to crizotinib (given that there are three drugs mentioned in the title)',
 'CRC is mentioned once in the introduction as an example of a disease associated with ROS1: "ROS1 plays an important role in different malignancies including glioblastoma, colorectal cancer, gastric adenocarcinoma..."',
 'Crizotinib is mentioned exclusively in the context of the treatment of lung cancer: "After Crizotinib approval by FDA for the management of ALK-rearranged lung cancer..."',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 'CRC is mentioned in the list of tumors in which ALK inhibitor activity is described ("colorectal, neuroendocrine, ovarian, pancreatic, renal, and thyroid cancer"), but this is only a mention in the list, and not the subject of primary research',
 'The review does not specifically target crizotinib for colorectal cancer - it is a review where CRC is just one of many tumor types mentioned. Without the full text, it is unclear how much detail the use of crizotinib in CRC is covered',
 'The abstract provides response rates (~50-85%), but these relate to approved indications (NSCLC, IMT, ALCL), not CRC',
 'The current study includes patients with a mixed population of solid tumors, not focusing on CRC. Although the Background section mentions a previous study on CRC xenografts (“We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth”). The Methods section states: "patients with advanced solid tumors received PD-0325901 with crizotinib" - without mentioning CRC as a specific population',
 'There is no indication in the abstract that the 25 patients included patients with CRC or that CRC was the target indication. Crizotinib used in combination with PD-0325901 in a mixed population',
 'Evaluates the effectiveness of the PD-0325901/crizotinib combination for solid tumors in general: "The best clinical response was stable disease in seven patients (29%)." Outcome is presented for the entire cohort, without breakdown by tumor type',
 'CRC cells in vitro (“specifically binds to c-Met in CRC cells”), mice with CRC tumors in vivo (“c-Met positive tumor-bearing mice”), etc.',
 'Used as a structural basis for the creation of a diagnostic fluorescent probe Crizotinib-PEG4-MPA. The text states: "we have developed a new small molecular fluorescence probe, namely Crizotinib-PEG4-MPA" - this is a modified molecule where crizotinib serves as a targeting element for binding to c-Met, but not as an independent drug for treatment',
 'The diagnostic effectiveness of the fluorescent probe is assessed, not the therapeutic effectiveness',
 '"We analyzed 26 MSI-High and 558 non-MSI-High CRC tumors", "We tested CRC cell lines", "Using an in-vivo CRC xenograft model"',
 '"tested CRC cell lines for sensitivity to MMC plus crizotinib" и "combined crizotinib and MMC therapy"',
 'In vitro:"increased apoptosis" и "synergistic anti-cancer effect (CI = 0.006-0.74)" In vivo: "reduced tumor growth with combined crizotinib and MMC therapy (p = 0.0088)"',
 'CRC is mentioned once in the list of diseases associated with ROS1 rearrangements: "including glioblastoma, non-small cell lung cancer (NSCLC), cholangiocarcinoma, ovarian cancer, gastric adenocarcinoma, colorectal cancer, inflammatory myofibroblastic tumor, angiosarcoma, and epithelioid hemangioendothelioma"',
 'Crizotinib is mentioned in the context of lung cancer treatment: "Targeting ROS1 fusion proteins with the small-molecule inhibitor crizotinib is showing promise as an effective therapy in patients with NSCLC whose tumors are positive for these genetic abnormalities."',
 'The article does not describe the assessment of the therapeutic efficacy of crizotinib in the treatment of colorectal cancer',
 '"colorectal cancer (CRC) cell lines" и "metastatic and orthotopic animal models of colon cancer"',
 '"combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib)" на моделях CRC',
 '"significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer"',
 'Among the responders, patients with CRC were mentioned, but the study did not focus on them. There are no separate models, cell lines or detailed analysis of only this group',
 'Crizotinib is not mentioned in the abstract. Study Evaluates Entrechtinib',
 'The study is evaluating entrechtinib. There is simply no data on the therapeutic efficacy of crizotinib for CRC.',
 'Human colon carcinoma cells and animal models were used',
 'It was indicated that inhibition of the MTH1 enzyme with (S)-crizotinib caused an increase in single-strand DNA breaks and activated DNA repair in human colon carcinoma cells',
 '1) increase in single-strand DNA breaks and activation of DNA repair in colon carcinoma cells 2) effective suppression of tumor growth in animal models',
 'CRC is mentioned once in the list, but only in the context of the KRAS biomarker and the drugs cetuximab/panitumumab. The object being studied is biomarkers, not diseases',
 'Crizotinib is mentioned in the abstract, but exclusively in relation to non-small cell lung cancer and the EML4-ALK biomarker',
 'All discussions of the effectiveness of crizotinib apply to NSCLC',
 'CRC is mentioned once in the list of examples: "the use of the monoclonal antibodies (trastuzumab and cetuximab) in HER2-positive breast cancer and wild-type KRAS colorectal cancer"',
 'Crizotinib in the article is associated with CML, GIST and NSCLC',
 'Crizotinib is not being studied for CRC. The article cannot evaluate its therapeutic effectiveness',
 'CRC is mentioned once in the introduction as a general example of malignancies in which rearrangements of receptor tyrosine kinases have been described',
 'Crizotinib is mentioned in the Background section in the context of treating NSCLC',
 'The conclusion makes a general conclusion about the feasibility of studying ROS1 inhibitors (without specifying a specific drug) for a subgroup of patients with gastric cancer',
 'CRC is mentioned as one of the three main tumor types considered in the context of a review of approved drugs (bevacizumab, cetuximab), without presenting its own primary data or models',
 '"FDA-approved drugs like osimertinib and crizotinib... providing remarkable benefits in patients with EGFR-mutated or ALK-positive lung cancer"',
 'All efficacy data mentioned are for either lung cancer (for crizotinib) or CRC (for bevacizumab and cetuximab)',
 'The study focused on CRC. It uses the TCGA and GEO databases containing samples from patients with CRC ("The Cancer Genome Atlas (TCGA) and Gene Expression Omnibus (GEO) databases were implemented to screen out RRAGs significantly associated with survival")',
 '"Immunonomic environment analysis, immunotherapy response prediction, enrichment analysis, tumor mutation analysis and drug prediction were performed in risk groups." The potential sensitivity of crizotinib was mathematically modeled',
 'The study provides predicted sensitivity but does not report any biologically or clinically relevant outcomes (such as apoptosis, tumor growth inhibition, survival, etc.) in response to crizotinib',
 'The study uses clinically relevant models - 3D CRC cultures ("patient-derived 3D colorectal cancer cultures")',
 'Study testing (S)-enantiomer of crizotinib as an intervention in 3D CRC cultures',
 'Эффективность: "reduce cancer cell viability"; "reduced tyrosine phosphorylation of c-MET and ErbB3"; "induced DNA damage"',
 '"A patient with metastatic BRAF-mutated colorectal cancer" и "In BRAF-mutated colorectal cancer cells"',
 '"the patient was treated with the dual ALK-MET inhibitor crizotinib plus vemurafenib"',
 'Clinical outcome: The patient had a rapid and robust clinical response to the new therapy regimen. Biological/preclinical outcome: The combination of BRAF and MET inhibition (crizotinib) was shown in vitro to overcome acquired resistance to previous therapy',
 'Study describes inflammatory myofibroblastic tumor',
 'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 'Study focused on CRC',
 'Crizotinib is being investigated as the active therapeutic component of the Crizotinib-IR808 conjugate. The conjugate is used for chemophototherapy, where crizotinib acts as a chemotherapeutic agent in combination with phototherapy',
 'Study evaluates therapeutic efficacy of crizotinib-containing conjugate based on biologically relevant preclinical outcomes',
 'Study describes a patient with an inflammatory myofibroblastic tumor of the rectoanal region',
 'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 '"the TRKA-dependent colorectal carcinoma KM12"; "Oral administration of entrectinib to tumor-bearing mice induced regression in relevant human xenograft tumors, including the TRKA-dependent colorectal carcinoma KM12"; "objective responses to a TRK inhibitor in colorectal carcinoma"',
 'Crizotinib is mentioned as an example of an already known selective kinase inhibitor, the effectiveness of which has been demonstrated in ALK/ROS1-positive tumors: "selective kinase inhibitors such as crizotinib, ceritinib, and alectinib"',
 'Therapeutic efficacy for CRC has not been assessed',
 'CRC is mentioned once in the abstract in the context that combined BRAF+MEK inhibition is not approved for it (“FDA approved for BRAF V600E-mutant solid tumors except for colorectal cancer”)',
 'Crizotinib is being studied in combination with vemurafenib in the general population (solid tumors in general)',
 'Study evaluates OS, PFS and ORR for entire solid tumor cohort',
 '"The LoVo colon cancer cell line"',
 'Crizotinib applied as an experimental treatment to CRC spheroids',
 'The study evaluates the biological effect of crizotinib in a 3D model of CRC. Although the focus of the article is on validating a new measurement method, the authors demonstrate that treatment with crizotinib has an effect on the biological parameters of the spheroids (changes in mass density and, as a result, structural integrity).',
 'The study included two independent clinical cohorts of patients with CRC (n=363 and n=390), clinical tissue samples ("clinical CRC tissues"), and also included cellular models to assess migration and invasion',
 '"the c-MET inhibitor crizotinib blocked the HGF/STAT3/SOX13/c-MET axis"',
 '"significantly inhibiting SOX13-mediated CRC migration, invasion and metastasis"',
 'The study focuses on hepatocellular carcinoma',
 'Crizotinib is being used and is being studied as an intervention for hepatocellular carcinoma',
 'Because the study does not include CRC nor does it test crizotinib, its therapeutic efficacy for CRC cannot be assessed.',
 'CRC is mentioned once in the list of rare locations where ROS1 fusions can occur',
 '"Crizotinib was the first inhibitor approved... for the treatment of ROS1-positive non-small cell lung cancer"',
 'The article does not evaluate the effectiveness of crizotinib in CRC',
 'Uses a tissue microarray of colorectal tumors, as well as 3 well-known CRC cell lines with the KRAS mutation: HCT116, DLD1 and LoVo',
 '"used a small molecule inhibitor of c-Met, crizotinib, in cetuximab-resistant, mutant KRAS-driven colorectal cancer cell lines"',
 'The study evaluates biologically and clinically relevant outcomes of crizotinib in combination with radiation. Specific quantitative data provided',
 'Research about CRC. It uses data from The Cancer Genome Atlas (TCGA) specifically for the PTPRK-RSPO3 fusion CRC subtype',
 'Crizotinib was identified through bioinformatics analysis of target-drug networks.',
 'Therapeutic efficacy has not been assessed',
 '"RNA sequencing of formalin-fixed, paraffin-embedded (FFPE) cancer tissue samples of 23 CRC patients"',
 '"Patients were treated by... crizotinib... as monotherapy or in combination with chemotherapy"',
 'The abstract provides algorithm quality metrics (AUC, Hazard ratio) for bevacizumab, but does not provide specific data on the actual therapeutic efficacy of crizotinib (for example, ORR, PFS or OS specifically for the crizotinib-treated cohort). The abstract does not allow an unambiguous assessment of the clinical efficacy of crizotinib as such.',
 'CRC is mentioned once in the list of diseases in the pathogenesis of which ALK may play a role',
 'Crizotinib is mentioned in the context of treating NSCLC',
 'Therapeutic efficacy for CRC has not been assessed',
 '"Thirty-six RASMT metastatic CRC patients were enrolled in the dose expansion"',
 '"assessed safety and initial efficacy of the MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in RASMT advanced CRC patients"',
 'Эффективность: "Best clinical response within the RASMT CRC cohort was stable disease in seven patients (24%)", "no objective responses observed"',
 '"expression profiles and clinical characteristics of CRC from the Gene Expression Omnibus (GEO) database and the Cancer Genome Atlas (TCGA) database"',
 'The drug is mathematically predicted to be potentially effective for a subgroup of patients at high immune risk (“S-crizotinib might have potential therapeutic implications”)',
 'Therapeutic efficacy has not been assessed',
 'The study represents a general screen of 1402 chemical compounds for their immunomodulatory potential ex vivo on peripheral mononuclear leukocytes. Although T cell interaction with "cancer cells" is mentioned, there is no indication in the abstract that these are CRC cells',
 'Crizotinib is being studied for its immunomodulatory properties (the ability to alter interactions between cells of the immune system)',
 'The study evaluates the effect of crizotinib on immune interactions rather than antitumor activity',
 '"human epithelial colorectal adenocarcinoma Caco-2 cell line"',
 '"Crizotinib are selected to test their cytotoxic effects on human epithelial colorectal adenocarcinoma Caco-2 cell line"',
 'The results indicate that crizotinib exhibits moderate cytotoxicity against CRC Caco-2 cells',
 'A review article on clinical findings and methods for detecting ROS1 in clinical laboratories. Colorectal carcinoma is mentioned once in the list of tumors where ROS1 rearrangements can occur',
 '"crizotinib has been shown to be an effective inhibitor of ROS1 and has received Food and Drug Administration approval for treatment of advanced NSCLC"',
 'Therapeutic efficacy cannot be assessed for CRC',
 'The study includes men with cancer, but there is no mention of CRC in the abstract',
 'The drug is not being studied specifically for CRC',
 'The study evaluates endocrine side effects (levels of total and free testosterone, LH, FSH, androgen deficiency symptoms) rather than antitumor activity',
 '"ARID1A-deficient colorectal cancer (CRC) cells", "in vitro and in xenograft tumor models"',
 '"c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells…"ъ',
 '"selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models", "diminishes GPX4 expression, resulting in elevated lipid peroxidation and glutathione depletion, ultimately inducing ferroptosis"',
 'CRC is mentioned once in the list of diseases associated with ALK rearrangements',
 'Crizotinib is being discussed in the context of treating NSCLC',

In [ ]:
dfo.iloc[:,4:-1] = np.array([i.text for i in r]).reshape(-1,3)
#dfo.to_csv('new_criteria_ana_en2.csv',index=False)

In [28]:
dfo.iloc[:,4:-1].values

array([['The article describes the clinical case of a 19-year-old patient with malignant peritoneal mesothelioma',
        'Crizotinib has been used to treat mesothelioma',
        'The effectiveness of crizotinib for CRC has not been assessed.'],
       ['"16 colorectal cancer cases"',
        'The abstract states that patients received inhibitors of various signaling pathways, including ALK/ROS1. Although crizotinib is an ALK/ROS1 inhibitor, it is not explicitly named in the abstract. We cannot confirm that it was the specific drug used in patients (it could be ceritinib, alectinib, lorlatinib, etc.)',
        'The abstract provides general data for the cohort (4 patients with CRC had a response), but is not linked to a specific drug.'],
       ['This is a review article summarizing current advances in targeted therapy for solid tumors. It does not include original patients, models or samples',
        'Crizotinib is mentioned in the abstract, but in association with NSCLC',
        'Therapeutic efficacy for CRC has not been assessed'],
       ['The study uses the CRC cell line Colo205 and related animal tumor models',
        'It is stated that crizotinib (both monotherapy and combination) was used to evaluate the effect on metastasis, and this effect was observed in all models tested, including Colo205',
        'The study evaluates the biologically and clinically relevant preclinical outcome of reduced metastasis'],
       ['The abstract mentions CRC as one example of tumors where ROS1 rearrangements may be observed',
        'Crizotinib is mentioned as a drug to which patients have developed resistance',
        'The study evaluates the effectiveness of the new drug DS-6051b, not crizotinib'],
       ['CRC is mentioned as an example ("KRAS against the use of cetuximab and panitumumab in colorectal cancer")',
        'Crizotinib mentioned in the context of NSCLC and ALK fusions',
        'The article does not evaluate the effectiveness of crizotinib in CRC'],
       ['A cohort of 1889 CRC samples is analyzed',
        'Crizotinib is mentioned in the introduction as a drug that has shown good results in the treatment of lung cancer with ALK/ROS1 rearrangements',
        'Therapeutic efficacy assessment for CRC is not available'],
       ['CRC cell line - KM12SM ("the KM12SM colorectal cancer cells containing the TPM3-NTRK1 gene fusion"). Corresponding animal models are also used (“in in vivo KM12SM cell models”)',
        'In vitro: "KM12SM cells were sensitive to the tropomyosin-related kinase-A inhibitors crizotinib and entrectinib". In vivo: "in in vivo KM12SM cell models, treatment with crizotinib delayed the progression of liver metastases..."',
        'The antitumor activity of crizotinib in the CRC model (KM12SM) is assessed by delaying the progression of metastases: “treatment with crizotinib delayed the progression of liver metastases, but not that of brain tumors”'],
       ['"human colorectal cancer (CRC) cell line (HCA-7)"; "CRC tissue microarray"',
        '"Addition of the dual MET/RON tyrosine kinase inhibitor, crizotinib, restored cetuximab sensitivity in SC." Crizotinib is used to overcome cetuximab resistance in a CRC model',
        'Evaluates the therapeutic efficacy of crizotinib based on the biologically significant outcome of “restored cetuximab sensitivity in SC.”'],
       ['CRC is mentioned only once in the introduction as an example of a disease associated with ROS1 ("which is involved in the formation of non-small cell lung cancer (NSCLC), gastric adenocarcinoma, colorectal cancer, and other malignant tumors")',
        'Crizotinib is mentioned in the context of treatment of NSCLC: 1. "only crizotinib was approved for the treatment of advanced ROS1-positive NSCLC" 2. "Since the approval of crizotinib as multi-targeted ALK/MET/ROS1 kinase inhibitor for ALK-mutated NSCLC therapy"',
        'All discussion of the effectiveness of crizotinib applies to NSCLC'],
       ['The title refers to a patient with metastatic colorectal cancer: "Metastatic Colorectal Carcinoma Patient". There is a description of a patient with CRC',
        'Crizotinib (along with Alectinib and Lorlatinib) was used as a treatment for the patient: "Clinical Responses to Crizotinib, Alectinib, and Lorlatinib..."',
        'The name indicates "Clinical Responses", which involves assessing clinical response. However, without an abstract it is impossible to confirm: Which outcomes were assessed (ORR, PFS, OS, etc.); Was quantitative data provided; What was the specific response to crizotinib (given that there are three drugs mentioned in the title)'],
       ['CRC is mentioned once in the introduction as an example of a disease associated with ROS1: "ROS1 plays an important role in different malignancies including glioblastoma, colorectal cancer, gastric adenocarcinoma..."',
        'Crizotinib is mentioned exclusively in the context of the treatment of lung cancer: "After Crizotinib approval by FDA for the management of ALK-rearranged lung cancer..."',
        'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy'],
       ['CRC is mentioned in the list of tumors in which ALK inhibitor activity is described ("colorectal, neuroendocrine, ovarian, pancreatic, renal, and thyroid cancer"), but this is only a mention in the list, and not the subject of primary research',
        'The review does not specifically target crizotinib for colorectal cancer - it is a review where CRC is just one of many tumor types mentioned. Without the full text, it is unclear how much detail the use of crizotinib in CRC is covered',
        'The abstract provides response rates (~50-85%), but these relate to approved indications (NSCLC, IMT, ALCL), not CRC'],
       ['The current study includes patients with a mixed population of solid tumors, not focusing on CRC. Although the Background section mentions a previous study on CRC xenografts (“We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth”). The Methods section states: "patients with advanced solid tumors received PD-0325901 with crizotinib" - without mentioning CRC as a specific population',
        'There is no indication in the abstract that the 25 patients included patients with CRC or that CRC was the target indication. Crizotinib used in combination with PD-0325901 in a mixed population',
        'Evaluates the effectiveness of the PD-0325901/crizotinib combination for solid tumors in general: "The best clinical response was stable disease in seven patients (29%)." Outcome is presented for the entire cohort, without breakdown by tumor type'],
       ['CRC cells in vitro (“specifically binds to c-Met in CRC cells”), mice with CRC tumors in vivo (“c-Met positive tumor-bearing mice”), etc.',
        'Used as a structural basis for the creation of a diagnostic fluorescent probe Crizotinib-PEG4-MPA. The text states: "we have developed a new small molecular fluorescence probe, namely Crizotinib-PEG4-MPA" - this is a modified molecule where crizotinib serves as a targeting element for binding to c-Met, but not as an independent drug for treatment',
        'The diagnostic effectiveness of the fluorescent probe is assessed, not the therapeutic effectiveness'],
       ['"We analyzed 26 MSI-High and 558 non-MSI-High CRC tumors", "We tested CRC cell lines", "Using an in-vivo CRC xenograft model"',
        '"tested CRC cell lines for sensitivity to MMC plus crizotinib" и "combined crizotinib and MMC therapy"',
        'In vitro:"increased apoptosis" и "synergistic anti-cancer effect (CI = 0.006-0.74)" In vivo: "reduced tumor growth with combined crizotinib and MMC therapy (p = 0.0088)"'],
       ['CRC is mentioned once in the list of diseases associated with ROS1 rearrangements: "including glioblastoma, non-small cell lung cancer (NSCLC), cholangiocarcinoma, ovarian cancer, gastric adenocarcinoma, colorectal cancer, inflammatory myofibroblastic tumor, angiosarcoma, and epithelioid hemangioendothelioma"',
        'Crizotinib is mentioned in the context of lung cancer treatment: "Targeting ROS1 fusion proteins with the small-molecule inhibitor crizotinib is showing promise as an effective therapy in patients with NSCLC whose tumors are positive for these genetic abnormalities."',
        'The article does not describe the assessment of the therapeutic efficacy of crizotinib in the treatment of colorectal cancer'],
       ['"colorectal cancer (CRC) cell lines" и "metastatic and orthotopic animal models of colon cancer"',
        '"combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib)" на моделях CRC',
        '"significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer"'],
       ['Among the responders, patients with CRC were mentioned, but the study did not focus on them. There are no separate models, cell lines or detailed analysis of only this group',
        'Crizotinib is not mentioned in the abstract. Study Evaluates Entrechtinib',
        'The study is evaluating entrechtinib. There is simply no data on the therapeutic efficacy of crizotinib for CRC.'],
       ['Human colon carcinoma cells and animal models were used',
        'It was indicated that inhibition of the MTH1 enzyme with (S)-crizotinib caused an increase in single-strand DNA breaks and activated DNA repair in human colon carcinoma cells',
        '1) increase in single-strand DNA breaks and activation of DNA repair in colon carcinoma cells 2) effective suppression of tumor growth in animal models'],
       ['CRC is mentioned once in the list, but only in the context of the KRAS biomarker and the drugs cetuximab/panitumumab. The object being studied is biomarkers, not diseases',
        'Crizotinib is mentioned in the abstract, but exclusively in relation to non-small cell lung cancer and the EML4-ALK biomarker',
        'All discussions of the effectiveness of crizotinib apply to NSCLC'],
       ['CRC is mentioned once in the list of examples: "the use of the monoclonal antibodies (trastuzumab and cetuximab) in HER2-positive breast cancer and wild-type KRAS colorectal cancer"',
        'Crizotinib in the article is associated with CML, GIST and NSCLC',
        'Crizotinib is not being studied for CRC. The article cannot evaluate its therapeutic effectiveness'],
       ['CRC is mentioned once in the introduction as a general example of malignancies in which rearrangements of receptor tyrosine kinases have been described',
        'Crizotinib is mentioned in the Background section in the context of treating NSCLC',
        'The conclusion makes a general conclusion about the feasibility of studying ROS1 inhibitors (without specifying a specific drug) for a subgroup of patients with gastric cancer'],
       ['CRC is mentioned as one of the three main tumor types considered in the context of a review of approved drugs (bevacizumab, cetuximab), without presenting its own primary data or models',
        '"FDA-approved drugs like osimertinib and crizotinib... providing remarkable benefits in patients with EGFR-mutated or ALK-positive lung cancer"',
        'All efficacy data mentioned are for either lung cancer (for crizotinib) or CRC (for bevacizumab and cetuximab)'],
       ['The study focused on CRC. It uses the TCGA and GEO databases containing samples from patients with CRC ("The Cancer Genome Atlas (TCGA) and Gene Expression Omnibus (GEO) databases were implemented to screen out RRAGs significantly associated with survival")',
        '"Immunonomic environment analysis, immunotherapy response prediction, enrichment analysis, tumor mutation analysis and drug prediction were performed in risk groups." The potential sensitivity of crizotinib was mathematically modeled',
        'The study provides predicted sensitivity but does not report any biologically or clinically relevant outcomes (such as apoptosis, tumor growth inhibition, survival, etc.) in response to crizotinib'],
       ['The study uses clinically relevant models - 3D CRC cultures ("patient-derived 3D colorectal cancer cultures")',
        'Study testing (S)-enantiomer of crizotinib as an intervention in 3D CRC cultures',
        'Эффективность: "reduce cancer cell viability"; "reduced tyrosine phosphorylation of c-MET and ErbB3"; "induced DNA damage"'],
       ['"A patient with metastatic BRAF-mutated colorectal cancer" и "In BRAF-mutated colorectal cancer cells"',
        '"the patient was treated with the dual ALK-MET inhibitor crizotinib plus vemurafenib"',
        'Clinical outcome: The patient had a rapid and robust clinical response to the new therapy regimen. Biological/preclinical outcome: The combination of BRAF and MET inhibition (crizotinib) was shown in vitro to overcome acquired resistance to previous therapy'],
       ['Study describes inflammatory myofibroblastic tumor',
        'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
        'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy'],
       ['Study focused on CRC',
        'Crizotinib is being investigated as the active therapeutic component of the Crizotinib-IR808 conjugate. The conjugate is used for chemophototherapy, where crizotinib acts as a chemotherapeutic agent in combination with phototherapy',
        'Study evaluates therapeutic efficacy of crizotinib-containing conjugate based on biologically relevant preclinical outcomes'],
       ['Study describes a patient with an inflammatory myofibroblastic tumor of the rectoanal region',
        'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
        'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy'],
       ['"the TRKA-dependent colorectal carcinoma KM12"; "Oral administration of entrectinib to tumor-bearing mice induced regression in relevant human xenograft tumors, including the TRKA-dependent colorectal carcinoma KM12"; "objective responses to a TRK inhibitor in colorectal carcinoma"',
        'Crizotinib is mentioned as an example of an already known selective kinase inhibitor, the effectiveness of which has been demonstrated in ALK/ROS1-positive tumors: "selective kinase inhibitors such as crizotinib, ceritinib, and alectinib"',
        'Therapeutic efficacy for CRC has not been assessed'],
       ['CRC is mentioned once in the abstract in the context that combined BRAF+MEK inhibition is not approved for it (“FDA approved for BRAF V600E-mutant solid tumors except for colorectal cancer”)',
        'Crizotinib is being studied in combination with vemurafenib in the general population (solid tumors in general)',
        'Study evaluates OS, PFS and ORR for entire solid tumor cohort'],
       ['"The LoVo colon cancer cell line"',
        'Crizotinib applied as an experimental treatment to CRC spheroids',
        'The study evaluates the biological effect of crizotinib in a 3D model of CRC. Although the focus of the article is on validating a new measurement method, the authors demonstrate that treatment with crizotinib has an effect on the biological parameters of the spheroids (changes in mass density and, as a result, structural integrity).'],
       ['The study included two independent clinical cohorts of patients with CRC (n=363 and n=390), clinical tissue samples ("clinical CRC tissues"), and also included cellular models to assess migration and invasion',
        '"the c-MET inhibitor crizotinib blocked the HGF/STAT3/SOX13/c-MET axis"',
        '"significantly inhibiting SOX13-mediated CRC migration, invasion and metastasis"'],
       ['The study focuses on hepatocellular carcinoma',
        'Crizotinib is being used and is being studied as an intervention for hepatocellular carcinoma',
        'Because the study does not include CRC nor does it test crizotinib, its therapeutic efficacy for CRC cannot be assessed.'],
       ['CRC is mentioned once in the list of rare locations where ROS1 fusions can occur',
        '"Crizotinib was the first inhibitor approved... for the treatment of ROS1-positive non-small cell lung cancer"',
        'The article does not evaluate the effectiveness of crizotinib in CRC'],
       ['Uses a tissue microarray of colorectal tumors, as well as 3 well-known CRC cell lines with the KRAS mutation: HCT116, DLD1 and LoVo',
        '"used a small molecule inhibitor of c-Met, crizotinib, in cetuximab-resistant, mutant KRAS-driven colorectal cancer cell lines"',
        'The study evaluates biologically and clinically relevant outcomes of crizotinib in combination with radiation. Specific quantitative data provided'],
       ['Research about CRC. It uses data from The Cancer Genome Atlas (TCGA) specifically for the PTPRK-RSPO3 fusion CRC subtype',
        'Crizotinib was identified through bioinformatics analysis of target-drug networks.',
        'Therapeutic efficacy has not been assessed'],
       ['"RNA sequencing of formalin-fixed, paraffin-embedded (FFPE) cancer tissue samples of 23 CRC patients"',
        '"Patients were treated by... crizotinib... as monotherapy or in combination with chemotherapy"',
        'The abstract provides algorithm quality metrics (AUC, Hazard ratio) for bevacizumab, but does not provide specific data on the actual therapeutic efficacy of crizotinib (for example, ORR, PFS or OS specifically for the crizotinib-treated cohort). The abstract does not allow an unambiguous assessment of the clinical efficacy of crizotinib as such.'],
       ['CRC is mentioned once in the list of diseases in the pathogenesis of which ALK may play a role',
        'Crizotinib is mentioned in the context of treating NSCLC',
        'Therapeutic efficacy for CRC has not been assessed'],
       ['"Thirty-six RASMT metastatic CRC patients were enrolled in the dose expansion"',
        '"assessed safety and initial efficacy of the MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in RASMT advanced CRC patients"',
        'Эффективность: "Best clinical response within the RASMT CRC cohort was stable disease in seven patients (24%)", "no objective responses observed"'],
       ['"expression profiles and clinical characteristics of CRC from the Gene Expression Omnibus (GEO) database and the Cancer Genome Atlas (TCGA) database"',
        'The drug is mathematically predicted to be potentially effective for a subgroup of patients at high immune risk (“S-crizotinib might have potential therapeutic implications”)',
        'Therapeutic efficacy has not been assessed'],
       ['The study represents a general screen of 1402 chemical compounds for their immunomodulatory potential ex vivo on peripheral mononuclear leukocytes. Although T cell interaction with "cancer cells" is mentioned, there is no indication in the abstract that these are CRC cells',
        'Crizotinib is being studied for its immunomodulatory properties (the ability to alter interactions between cells of the immune system)',
        'The study evaluates the effect of crizotinib on immune interactions rather than antitumor activity'],
       ['"human epithelial colorectal adenocarcinoma Caco-2 cell line"',
        '"Crizotinib are selected to test their cytotoxic effects on human epithelial colorectal adenocarcinoma Caco-2 cell line"',
        'The results indicate that crizotinib exhibits moderate cytotoxicity against CRC Caco-2 cells'],
       ['A review article on clinical findings and methods for detecting ROS1 in clinical laboratories. Colorectal carcinoma is mentioned once in the list of tumors where ROS1 rearrangements can occur',
        '"crizotinib has been shown to be an effective inhibitor of ROS1 and has received Food and Drug Administration approval for treatment of advanced NSCLC"',
        'Therapeutic efficacy cannot be assessed for CRC'],

### back

In [77]:
dfo = pd.read_csv('new_criteria_ana_en2.csv')
dfo['PMID'] = dfo['PMID'].astype(str)
dfo[['s1','s2','s3']] = dfo[['s1','s2','s3']].astype(int)
dfo.head(2)

,PMID,s1,s2,s3,r1,r2,r3,accept
0,34766064,-1,-1,-1,The article describes the clinical case of a 1...,Crizotinib has been used to treat mesothelioma,The effectiveness of crizotinib for CRC has no...,False
1,32208873,1,-1,-1,"""16 colorectal cancer cases""",The abstract states that patients received inh...,The abstract provides general data for the coh...,False

In [78]:
from sklearn.model_selection import train_test_split
X = dfo.iloc[:,:1]
y = dfo.iloc[:,]
# stratify by accept/not accept. maybe instead by [1,1,0]?
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, 
                                                    random_state=42,stratify=dfo.accept)

In [123]:
import main
df_p_e = main.run_screening(pmid_list=X_train.PMID.values, 
                            fin_condition='Colorectal cancer', 
                            treatment='Crizotinib',
                            ps_thresh = [1,1,0], real=False)

INFO:root:COLLECTING PAPER TEXTS
INFO:root:2.3204500675201416
INFO:root:SCREENING PAPERS
INFO:root:0.0074841976165771484

In [124]:
df_p_e.head(2)

,PMID,s1,s2,s3,r1,r2,r3,Fin_text
0,34898475,1,1,0,The study explicitly focuses on 'colorectal ca...,The results section explicitly mentions 'S-cri...,The study identifies Crizotinib via 'in silico...,Identification of a novel immune signature for...
1,28320945,1,1,1,The study explicitly uses a 'human colorectal ...,The text states: 'Addition of the dual MET/RON...,The study evaluates therapeutic effectiveness ...,Three-dimensional culture system identifies a ...

In [80]:
y_train.head(2)

,PMID,s1,s2,s3,r1,r2,r3,accept
41,34898475,1,-1,-1,"""expression profiles and clinical characterist...",The drug is mathematically predicted to be pot...,Therapeutic efficacy has not been assessed,False
8,28320945,1,1,1,"""human colorectal cancer (CRC) cell line (HCA-...","""Addition of the dual MET/RON tyrosine kinase ...",Evaluates the therapeutic efficacy of crizotin...,True

In [128]:
errors_df = main.find_mistakes(df_p_e, y_train)
errors_df.head(1)

,PMID,num,Fin_text,s_pred,r_pred,s_expert,r_expert
3,22845480,1,Personalized medicine and pharmacogenetic biom...,1,The text explicitly mentions 'KRAS against the...,-1,"CRC is mentioned once in the list, but only in..."

In [136]:
from queries import papers_criteria as papers_criteria
error_one = errors_df.values[0]
pmid, num,abstract,model_score,model_rationale,expert_score,expert_rationale =  error_one

fin_condition='Colorectal cancer'
treatment='Crizotinib'

user_prompt = """
eligibility_criteria = "{eligibility_criteria}"
abstract = "{abstract}"
model_rationale = "{model_rationale}"
expert_rationale = "{expert_rationale}"
model_score = {model_score}
expert_score = {expert_score}
your_response = 
"""
user_prompt = user_prompt.format(eligibility_criteria = papers_criteria[num-1].format(treatment=treatment,
                                                                                      fin_condition=fin_condition),
                                 abstract=abstract,model_rationale=model_rationale,
                                 expert_rationale=expert_rationale,model_score=model_score,
                                 expert_score=expert_score)
print(user_prompt)

eligibility_criteria = "Does the study include patients, animal models, organoids, cell lines, or biological samples representing 'Colorectal cancer' as a studied disease/condition?"
abstract = "Personalized medicine and pharmacogenetic biomarkers: progress in molecular oncology testing.: : In the field of oncology, clinical molecular diagnostics and biomarker discoveries are constantly advancing as the intricate molecular mechanisms that transform a normal cell into an aberrant state in concert with the dysregulation of alternative complementary pathways are increasingly understood. Progress in biomarker technology, coupled with the companion clinical diagnostic laboratory tests, continue to advance this field, where individualized and customized treatment appropriate for each individual patient define the standard of care. Here, we discuss the current commonly used predictive pharmacogenetic biomarkers in clinical oncology molecular testing: BRAF V600E for vemurafenib in melanoma; EML4-ALK for crizotinib and EGFR for erlotinib and gefitinib in non-small-cell lung cancer; KRAS against the use of cetuximab and panitumumab in colorectal cancer; ERBB2 (HER2/neu) for trastuzumab in breast cancer; BCR-ABL for tyrosine kinase inhibitors in chronic myeloid leukemia; and PML/RARα for all-trans-retinoic acid and arsenic trioxide treatment for acute promyelocytic leukemia."
model_rationale = "The text explicitly mentions 'KRAS against the use of cetuximab and panitumumab in colorectal cancer', confirming that colorectal cancer is a studied disease/condition in the context of the biomarkers discussed."
expert_rationale = "CRC is mentioned once in the list, but only in the context of the KRAS biomarker and the drugs cetuximab/panitumumab. The object being studied is biomarkers, not diseases"
model_score = 1
expert_score = -1
your_response =

## fixing types of errors

In [ ]:
df = pd.read_csv('common_errors.csv',sep=';')
chosen_cols = df.columns[~df.columns.isin(['контекст/уточнения'])]
df = df[chosen_cols].dropna(how='all')
df['Оценка_Эксперт']=df['Оценка_Эксперт'].astype(int)
df['Новая оценка эксперта'] = df[['Новая оценка эксперта','Тип_ошибки']].apply(lambda x: x['Новая оценка эксперта'] \
                                                                               if x['Тип_ошибки']!='In silico вместо фактического применения' else None,
                                                                               axis=1)
df['Оценка_Эксперт'] = df[['Оценка_Эксперт','Новая оценка эксперта']].apply(lambda x: int(x['Новая оценка эксперта']) \
                                                     if not pd.isna(x['Новая оценка эксперта']) else x['Оценка_Эксперт'],
                                                     axis=1)
df['Обоснование_Эксперт'] = df[['Обоснование_Эксперт','Новое обосновение эксперта']].apply(lambda x: x['Новое обосновение эксперта'] \
                                                     if not pd.isna(x['Новое обосновение эксперта']) else x['Обоснование_Эксперт'],
                                                     axis=1)
df['Почему_ошибка'] = df[['Почему_ошибка','Новое почему ошибка']].apply(lambda x: x['Новое почему ошибка'] \
                                                     if not pd.isna(x['Новое почему ошибка']) else x['Почему_ошибка'],
                                                     axis=1)
df['Тип_ошибки'] = df[['Новый тип ошибки','Тип_ошибки']].apply(lambda x: x['Новый тип ошибки'] if (not pd.isna(x['Новый тип ошибки'])) else x['Тип_ошибки'],
                                                         axis=1)

'In silico вместо фактического применения'
'The model mistakes a diagnostic/imaging tool for a therapeutic intervention.'

df.loc[df['Тип_ошибки'].isin(['In silico вместо фактического применения',
                         'The model mistakes a diagnostic/imaging tool for a therapeutic intervention.']),
       'Тип_ошибки'] = 'The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.'
df.loc[df['Тип_ошибки']=='The criteria is partially met', 'Тип_ошибки'] = 'The criteria is only partially met'
print(df.shape, df[df['Оценка_ЛЛМ']!=df['Оценка_Эксперт']].shape)
df = df[df['Оценка_ЛЛМ']!=df['Оценка_Эксперт']].iloc[:,:8]
#df.to_csv('common_errors_fixed.csv',index=False)
df.head(2)

(40, 12) (35, 12)

,PMID_статьи,Номер_критерия,Оценка_ЛЛМ,Обоснование_LLM,Оценка_Эксперт,Обоснование_Эксперт,Почему_ошибка,Тип_ошибки
0,25139705.0,1.0,1.0,The text explicitly lists 'colorectal cancer' ...,-1.0,"Это обзорная статья, обобщающая текущие достиж...",LLM приняла упоминание КРР в обзоре как фокус ...,The model confuses background keywords with th...
1,31399568.0,1.0,1.0,The text explicitly states that 'ROS1 gene rea...,-1.0,В абстракте крр упомянут как один из примеров ...,LLM интерпретировала КРР как изучаемое заболев...,The model confuses background keywords with th...

In [60]:
df['Тип_ошибки'].value_counts()

Тип_ошибки
The model confuses background keywords with the paper's focus                                            14
The model treats 'not mentioned' as 'possible'                                                           11
The model mistakes a diagnostic/imaging/prognostic tool for an investigated therapeutic intervention.     5
The criteria is only partially met                                                                        2
The model equates keyword co-occurrence with keyword interaction.                                         1
The model mistakes a proposed idea for a concept under study.                                             1
The model confuses a general topic with the potential inclusion of specific data.                         1
Name: count, dtype: int64

## translate

In [5]:
%pip uninstall -y googletrans 
%pip install googletrans-curl

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping googletrans as it is not installed.

Collecting googletrans-curl
  Using cached googletrans_curl-4.1.0-py3-none-any.whl.metadata (9.1 kB)
Collecting curl-cffi>=0.7.0 (from googletrans-curl)
  Using cached curl_cffi-0.16.3-cp310-abi3-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: httpx>=0.27.2 in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx[http2]>=0.27.2->googletrans-curl) (0.28.1)
Collecting cffi>=2.0.0 (from curl-cffi>=0.7.0->googletrans-curl)
  Using cached cffi-2.1.1-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Requirement already satisfied: certifi>=2024.2.2 in d:\programs\anaconda\envs\llms\lib\site-packages (from curl-cffi>=0.7.0->googletrans-curl) (2026.1.4)
Collecting pycparser (from cffi>=2.0.0->curl-cffi>=0.7.0->googletrans-curl)
  Using cached pycparser-3.11-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: anyio in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (4.12.1)
Requirement already satisfied: httpcore==1.* in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (1.0.9)
Requirement already satisfied: idna in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (3.11)
Requirement already satisfied: h11>=0.16 in d:\programs\anaconda\envs\llms\lib\site-packages (from httpcore==1.*->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (0.16.0)
Requirement already satisfied: h2<5,>=3 in d:\programs\anaconda\envs\llms\lib\site-packages (from httpx[http2]>=0.27.2->googletrans-curl) (4.3.0)
Requirement already satisfied: hyperframe<7,>=6.1 in d:\programs\anaconda\envs\llms\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.27.2->googletrans-curl) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in d:\programs\anaconda\envs\llms\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.27.2->googletrans-curl) (4.1.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in d:\programs\anaconda\envs\llms\lib\site-packages (from anyio->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (1.3.0)
Requirement already satisfied: typing_extensions>=4.5 in d:\programs\anaconda\envs\llms\lib\site-packages (from anyio->httpx>=0.27.2->httpx[http2]>=0.27.2->googletrans-curl) (4.15.0)
Using cached googletrans_curl-4.1.0-py3-none-any.whl (21 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 8.5 MB/s  0:00:00
Downloading cffi-2.1.1-cp310-cp310-win_amd64.whl (185 kB)
Downloading pycparser-3.11-py3-none-any.whl (51 kB)
Installing collected packages: pycparser, cffi, curl-cffi, googletrans-curl

   ---------- ----------------------------- 1/4 [cffi]
   ---------- ----------------------------- 1/4 [cffi]
   ---------- ----------------------------- 1/4 [cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   -------------------- ------------------- 2/4 [curl-cffi]
   ------------------------------ --------- 3/4 [googletrans-curl]
   ---------------------------------------- 4/4 [googletrans-curl]

Successfully installed cffi-2.1.1 curl-cffi-0.16.3 googletrans-curl-4.1.0 pycparser-3.11
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script cffi-gen-src.exe is installed in 'd:\Programs\Anaconda\envs\llms\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script curl-cffi.exe is installed in 'd:\Programs\Anaconda\envs\llms\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script translate.exe is installed in 'd:\Programs\Anaconda\envs\llms\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
from googletrans import SyncTranslator
import re
translator = SyncTranslator()
text=['В статье описывается клинический случай 19-летнего пациента с злокачественной перитонеальной мезотелиомой',
       'Кризотиниб применялся для лечения мезотелиомы',
       'Эффективность кризотиниба для крр не оценивается','Кризотиниб упоминается в абстракте, но в связи с нмрл и транслокациями ALK']
text = [re.sub(r'\b[нН][мМ][Рр][лЛ]\b','NSCLC', re.sub(r'\b[Кк][Рр][Рр]\b','CRC',i)) for i in text]
r = translator.translate([i for i in text], dest="en")
[i.text for i in r]#.text

['The article describes the clinical case of a 19-year-old patient with malignant peritoneal mesothelioma',
 'Crizotinib has been used to treat mesothelioma',
 'The effectiveness of crizotinib for CRC has not been assessed',
 'Crizotinib is mentioned in the abstract, but in association with NSCLC and ALK translocations']

In [ ]:
from googletrans import SyncTranslator
import re
translator = SyncTranslator()
text = (dfo.iloc[:,4:].values).reshape(-1)
text = [re.sub(r'\b[нН][мМ][Рр][лЛ]\b','NSCLC', re.sub(r'\b[Кк][Рр][Рр]\b','CRC',i)) for i in text]
r = translator.translate([i for i in text], dest="en")
[i.text for i in r]#.text

['The article describes the clinical case of a 19-year-old patient with malignant peritoneal mesothelioma',
 'Crizotinib has been used to treat mesothelioma',
 'The effectiveness of crizotinib for CRC has not been assessed.',
 '"16 colorectal cancer cases"',
 'The abstract states that patients received inhibitors of various signaling pathways, including ALK/ROS1. Although crizotinib is an ALK/ROS1 inhibitor, it is not explicitly named in the abstract. We cannot confirm that it was the specific drug used in patients (it could be ceritinib, alectinib, lorlatinib, etc.)',
 'The abstract provides general data for the cohort (4 patients with CRC had a response), but is not linked to a specific drug.',
 'This is a review article summarizing current advances in targeted therapy for solid tumors. It does not include original patients, models or samples',
 'Crizotinib is mentioned in the abstract, but in association with NSCLC',
 'Therapeutic efficacy for CRC has not been assessed',
 'The study uses the CRC cell line Colo205 and related animal tumor models',
 'It is stated that crizotinib (both monotherapy and combination) was used to evaluate the effect on metastasis, and this effect was observed in all models tested, including Colo205',
 'The study evaluates the biologically and clinically relevant preclinical outcome of reduced metastasis',
 'The abstract mentions CRC as one example of tumors where ROS1 rearrangements may be observed',
 'Crizotinib is mentioned as a drug to which patients have developed resistance',
 'The study evaluates the effectiveness of the new drug DS-6051b, not crizotinib',
 'CRC is mentioned as an example ("KRAS against the use of cetuximab and panitumumab in colorectal cancer")',
 'Crizotinib mentioned in the context of NSCLC and ALK fusions',
 'The article does not evaluate the effectiveness of crizotinib in CRC',
 'A cohort of 1889 CRC samples is analyzed',
 'Crizotinib is mentioned in the introduction as a drug that has shown good results in the treatment of lung cancer with ALK/ROS1 rearrangements',
 'Therapeutic efficacy assessment for CRC is not available',
 'CRC cell line - KM12SM ("the KM12SM colorectal cancer cells containing the TPM3-NTRK1 gene fusion"). Corresponding animal models are also used (“in in vivo KM12SM cell models”)',
 'In vitro: "KM12SM cells were sensitive to the tropomyosin-related kinase-A inhibitors crizotinib and entrectinib". In vivo: "in in vivo KM12SM cell models, treatment with crizotinib delayed the progression of liver metastases..."',
 'The antitumor activity of crizotinib in the CRC model (KM12SM) is assessed by delaying the progression of metastases: “treatment with crizotinib delayed the progression of liver metastases, but not that of brain tumors”',
 '"human colorectal cancer (CRC) cell line (HCA-7)"; "CRC tissue microarray"',
 '"Addition of the dual MET/RON tyrosine kinase inhibitor, crizotinib, restored cetuximab sensitivity in SC." Crizotinib is used to overcome cetuximab resistance in a CRC model',
 'Evaluates the therapeutic efficacy of crizotinib based on the biologically significant outcome of “restored cetuximab sensitivity in SC.”',
 'CRC is mentioned only once in the introduction as an example of a disease associated with ROS1 ("which is involved in the formation of non-small cell lung cancer (NSCLC), gastric adenocarcinoma, colorectal cancer, and other malignant tumors")',
 'Crizotinib is mentioned in the context of treatment of NSCLC: 1. "only crizotinib was approved for the treatment of advanced ROS1-positive NSCLC" 2. "Since the approval of crizotinib as multi-targeted ALK/MET/ROS1 kinase inhibitor for ALK-mutated NSCLC therapy"',
 'All discussion of the effectiveness of crizotinib applies to NSCLC',
 'The title refers to a patient with metastatic colorectal cancer: "Metastatic Colorectal Carcinoma Patient". There is a description of a patient with CRC',
 'Crizotinib (along with Alectinib and Lorlatinib) was used as a treatment for the patient: "Clinical Responses to Crizotinib, Alectinib, and Lorlatinib..."',
 'The name indicates "Clinical Responses", which involves assessing clinical response. However, without an abstract it is impossible to confirm: Which outcomes were assessed (ORR, PFS, OS, etc.); Was quantitative data provided; What was the specific response to crizotinib (given that there are three drugs mentioned in the title)',
 'CRC is mentioned once in the introduction as an example of a disease associated with ROS1: "ROS1 plays an important role in different malignancies including glioblastoma, colorectal cancer, gastric adenocarcinoma..."',
 'Crizotinib is mentioned exclusively in the context of the treatment of lung cancer: "After Crizotinib approval by FDA for the management of ALK-rearranged lung cancer..."',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 'CRC is mentioned in the list of tumors in which ALK inhibitor activity is described ("colorectal, neuroendocrine, ovarian, pancreatic, renal, and thyroid cancer"), but this is only a mention in the list, and not the subject of primary research',
 'The review does not specifically target crizotinib for colorectal cancer - it is a review where CRC is just one of many tumor types mentioned. Without the full text, it is unclear how much detail the use of crizotinib in CRC is covered',
 'The abstract provides response rates (~50-85%), but these relate to approved indications (NSCLC, IMT, ALCL), not CRC',
 'The current study includes patients with a mixed population of solid tumors, not focusing on CRC. Although the Background section mentions a previous study on CRC xenografts (“We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth”). The Methods section states: "patients with advanced solid tumors received PD-0325901 with crizotinib" - without mentioning CRC as a specific population',
 'There is no indication in the abstract that the 25 patients included patients with CRC or that CRC was the target indication. Crizotinib used in combination with PD-0325901 in a mixed population',
 'Evaluates the effectiveness of the PD-0325901/crizotinib combination for solid tumors in general: "The best clinical response was stable disease in seven patients (29%)." Outcome is presented for the entire cohort, without breakdown by tumor type',
 'CRC cells in vitro (“specifically binds to c-Met in CRC cells”), mice with CRC tumors in vivo (“c-Met positive tumor-bearing mice”), etc.',
 'Used as a structural basis for the creation of a diagnostic fluorescent probe Crizotinib-PEG4-MPA. The text states: "we have developed a new small molecular fluorescence probe, namely Crizotinib-PEG4-MPA" - this is a modified molecule where crizotinib serves as a targeting element for binding to c-Met, but not as an independent drug for treatment',
 'The diagnostic effectiveness of the fluorescent probe is assessed, not the therapeutic effectiveness',
 '"We analyzed 26 MSI-High and 558 non-MSI-High CRC tumors", "We tested CRC cell lines", "Using an in-vivo CRC xenograft model"',
 '"tested CRC cell lines for sensitivity to MMC plus crizotinib" и "combined crizotinib and MMC therapy"',
 'In vitro:"increased apoptosis" и "synergistic anti-cancer effect (CI = 0.006-0.74)" In vivo: "reduced tumor growth with combined crizotinib and MMC therapy (p = 0.0088)"',
 'CRC is mentioned once in the list of diseases associated with ROS1 rearrangements: "including glioblastoma, non-small cell lung cancer (NSCLC), cholangiocarcinoma, ovarian cancer, gastric adenocarcinoma, colorectal cancer, inflammatory myofibroblastic tumor, angiosarcoma, and epithelioid hemangioendothelioma"',
 'Crizotinib is mentioned in the context of lung cancer treatment: "Targeting ROS1 fusion proteins with the small-molecule inhibitor crizotinib is showing promise as an effective therapy in patients with NSCLC whose tumors are positive for these genetic abnormalities."',
 'Crizotinib is not being studied for CRC - the article cannot assess its therapeutic efficacy',
 '"colorectal cancer (CRC) cell lines" и "metastatic and orthotopic animal models of colon cancer"',
 '"combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib)" на моделях CRC',
 '"significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer"',
 'Among the responders, patients with CRC were mentioned, but the study did not focus on them. There are no separate models, cell lines or detailed analysis of only this group',
 'Crizotinib is not mentioned in the abstract. Study Evaluates Entrechtinib',
 'The study is evaluating entrechtinib. There is simply no data on the therapeutic efficacy of crizotinib for CRC.',
 'Human colon carcinoma cells and animal models were used',
 'It was indicated that inhibition of the MTH1 enzyme with (S)-crizotinib caused an increase in single-strand DNA breaks and activated DNA repair in human colon carcinoma cells',
 '1) increase in single-strand DNA breaks and activation of DNA repair in colon carcinoma cells 2) effective suppression of tumor growth in animal models',
 'CRC is mentioned once in the list, but only in the context of the KRAS biomarker and the drugs cetuximab/panitumumab',
 'Crizotinib is mentioned in the abstract, but exclusively in relation to non-small cell lung cancer and the EML4-ALK biomarker',
 'All discussions of the effectiveness of crizotinib apply to NSCLC',
 'CRC is mentioned once in the list of examples: "the use of the monoclonal antibodies (trastuzumab and cetuximab) in HER2-positive breast cancer and wild-type KRAS colorectal cancer"',
 'Crizotinib in the article is associated with CML, GIST and NSCLC',
 'Crizotinib is not being studied for CRC. The article cannot evaluate its therapeutic effectiveness',
 'CRC is mentioned once in the introduction as a general example of malignancies in which rearrangements of receptor tyrosine kinases have been described',
 'Crizotinib is mentioned in the Background section in the context of treating NSCLC',
 'The conclusion makes a general conclusion about the feasibility of studying ROS1 inhibitors (without specifying a specific drug) for a subgroup of patients with gastric cancer',
 'CRC is mentioned as one of the three main tumor types considered in the context of a review of approved drugs (bevacizumab, cetuximab), without presenting its own primary data or models',
 '"FDA-approved drugs like osimertinib and crizotinib... providing remarkable benefits in patients with EGFR-mutated or ALK-positive lung cancer"',
 'All efficacy data mentioned are for either lung cancer (for crizotinib) or CRC (for bevacizumab and cetuximab)',
 'The study focused on CRC. It uses the TCGA and GEO databases containing samples from patients with CRC ("The Cancer Genome Atlas (TCGA) and Gene Expression Omnibus (GEO) databases were implemented to screen out RRAGs significantly associated with survival")',
 'Crizotinib is mentioned in the context of computational prediction of drug sensitivity based on gene expression profiles: "drugs such as FTI-277, DMOG, and Crizotinib were more sensitive to low-risk group." This is a bioinformatics procedure (predicting IC50 values \u200b\u200busing algorithms such as pRRophetic) in which the drug is not actually applied to cells or patients, but rather its potential sensitivity is mathematically modeled',
 'The study provides predicted sensitivity but does not report any biologically or clinically relevant outcomes (such as apoptosis, tumor growth inhibition, survival, etc.) in response to crizotinib',
 'The study uses clinically relevant models - 3D CRC cultures ("patient-derived 3D colorectal cancer cultures")',
 'Study testing (S)-enantiomer of crizotinib as an intervention in 3D CRC cultures',
 'Эффективность: "reduce cancer cell viability"; "reduced tyrosine phosphorylation of c-MET and ErbB3"; "induced DNA damage"',
 '"A patient with metastatic BRAF-mutated colorectal cancer" и "In BRAF-mutated colorectal cancer cells"',
 '"the patient was treated with the dual ALK-MET inhibitor crizotinib plus vemurafenib"',
 'Clinical outcome: The patient had a rapid and robust clinical response to the new therapy regimen. Biological/preclinical outcome: The combination of BRAF and MET inhibition (crizotinib) was shown in vitro to overcome acquired resistance to previous therapy',
 'Study describes inflammatory myofibroblastic tumor',
 'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 'Study focused on CRC',
 'Crizotinib is being investigated as the active therapeutic component of the Crizotinib-IR808 conjugate. The conjugate is used for chemophototherapy, where crizotinib acts as a chemotherapeutic agent in combination with phototherapy',
 'Study evaluates therapeutic efficacy of crizotinib-containing conjugate based on biologically relevant preclinical outcomes',
 'Study describes a patient with an inflammatory myofibroblastic tumor of the rectoanal region',
 'Crizotinib is used to treat inflammatory myofibroblastic tumor, not CRC',
 'Because crizotinib is not being studied for CRC, the article cannot assess its therapeutic efficacy',
 '"the TRKA-dependent colorectal carcinoma KM12"; "Oral administration of entrectinib to tumor-bearing mice induced regression in relevant human xenograft tumors, including the TRKA-dependent colorectal carcinoma KM12"; "objective responses to a TRK inhibitor in colorectal carcinoma"',
 'Crizotinib is mentioned as an example of an already known selective kinase inhibitor, the effectiveness of which has been demonstrated in ALK/ROS1-positive tumors: "selective kinase inhibitors such as crizotinib, ceritinib, and alectinib"',
 'Therapeutic efficacy for CRC has not been assessed',
 'CRC is mentioned once in the abstract in the context that combined BRAF+MEK inhibition is not approved for it (“FDA approved for BRAF V600E-mutant solid tumors except for colorectal cancer”)',
 'Crizotinib is being studied in combination with vemurafenib in the general population (solid tumors in general)',
 'Study evaluates OS, PFS and ORR for entire solid tumor cohort',
 '"The LoVo colon cancer cell line"',
 'Crizotinib applied as an experimental treatment to CRC spheroids',
 'The study evaluates the biological effect of crizotinib in a 3D model of CRC. Although the focus of the article is on validating a new measurement method, the authors demonstrate that treatment with crizotinib has an effect on the biological parameters of the spheroids (changes in mass density and, as a result, structural integrity).',
 'The study included two independent clinical cohorts of patients with CRC (n=363 and n=390), clinical tissue samples ("clinical CRC tissues"), and also included cellular models to assess migration and invasion',
 '"the c-MET inhibitor crizotinib blocked the HGF/STAT3/SOX13/c-MET axis"',
 '"significantly inhibiting SOX13-mediated CRC migration, invasion and metastasis"',
 'The study focuses on hepatocellular carcinoma',
 'Crizotinib is being used and is being studied as an intervention for hepatocellular carcinoma',
 'Because the study does not include CRC nor does it test crizotinib, its therapeutic efficacy for CRC cannot be assessed.',
 'CRC is mentioned once in the list of rare locations where ROS1 fusions can occur',
 '"Crizotinib was the first inhibitor approved... for the treatment of ROS1-positive non-small cell lung cancer"',
 'The article does not evaluate the effectiveness of crizotinib in CRC',
 'Uses a tissue microarray of colorectal tumors, as well as 3 well-known CRC cell lines with the KRAS mutation: HCT116, DLD1 and LoVo',
 '"used a small molecule inhibitor of c-Met, crizotinib, in cetuximab-resistant, mutant KRAS-driven colorectal cancer cell lines"',
 'The study evaluates biologically and clinically relevant outcomes of crizotinib in combination with radiation. Specific quantitative data provided',
 'Research about CRC. It uses data from The Cancer Genome Atlas (TCGA) specifically for the PTPRK-RSPO3 fusion CRC subtype',
 'Crizotinib was identified through bioinformatics analysis of target-drug networks. The drug has not been tested on cells, animals or patients',
 'Therapeutic efficacy has not been assessed',
 '"RNA sequencing of formalin-fixed, paraffin-embedded (FFPE) cancer tissue samples of 23 CRC patients"',
 '"Patients were treated by... crizotinib... as monotherapy or in combination with chemotherapy"',
 'The abstract provides algorithm quality metrics (AUC, Hazard ratio) for bevacizumab, but does not provide specific data on the actual therapeutic efficacy of crizotinib (for example, ORR, PFS or OS specifically for the crizotinib-treated cohort). The abstract does not allow an unambiguous assessment of the clinical efficacy of crizotinib as such.',
 'CRC is mentioned once in the list of diseases in the pathogenesis of which ALK may play a role',
 'Crizotinib is mentioned in the context of treating NSCLC',
 'Therapeutic efficacy for CRC has not been assessed',
 '"Thirty-six RASMT metastatic CRC patients were enrolled in the dose expansion"',
 '"assessed safety and initial efficacy of the MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in RASMT advanced CRC patients"',
 'Эффективность: "Best clinical response within the RASMT CRC cohort was stable disease in seven patients (24%)", "no objective responses observed"',
 '"expression profiles and clinical characteristics of CRC from the Gene Expression Omnibus (GEO) database and the Cancer Genome Atlas (TCGA) database"',
 'The drug is mathematically predicted to be potentially effective for a subgroup of patients at high immune risk (“S-crizotinib might have potential therapeutic implications”)',
 'Therapeutic efficacy has not been assessed',
 'The study represents a general screen of 1402 chemical compounds for their immunomodulatory potential ex vivo on peripheral mononuclear leukocytes. Although T cell interaction with "cancer cells" is mentioned, there is no indication in the abstract that these are CRC cells',
 'Crizotinib is being studied for its immunomodulatory properties (the ability to alter interactions between cells of the immune system)',
 'The study evaluates the effect of crizotinib on immune interactions rather than antitumor activity',
 '"human epithelial colorectal adenocarcinoma Caco-2 cell line"',
 '"Crizotinib are selected to test their cytotoxic effects on human epithelial colorectal adenocarcinoma Caco-2 cell line"',
 'The results indicate that crizotinib exhibits moderate cytotoxicity against CRC Caco-2 cells',
 'Review article on clinical findings and methods for detecting ROS1 in clinical laboratories. Colorectal carcinoma is mentioned once in the list of tumors where ROS1 rearrangements can occur',
 '"crizotinib has been shown to be an effective inhibitor of ROS1 and has received Food and Drug Administration approval for treatment of advanced NSCLC"',
 'Therapeutic efficacy cannot be assessed for CRC',
 'The study includes men with cancer, but there is no mention of CRC in the abstract',
 'The drug is not being studied specifically for CRC',
 'The study evaluates endocrine side effects (levels of total and free testosterone, LH, FSH, androgen deficiency symptoms) rather than antitumor activity',
 '"ARID1A-deficient colorectal cancer (CRC) cells", "in vitro and in xenograft tumor models"',
 '"c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells…"ъ',
 '"selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models", "diminishes GPX4 expression, resulting in elevated lipid peroxidation and glutathione depletion, ultimately inducing ferroptosis"',

In [ ]:
dfo.iloc[:,4:] = np.array([i.text for i in r]).reshape(-1,3)
#dfo.to_csv('/content/drive/MyDrive/new_criteria_ana_en.csv',index=False)